### ISSUE TITLE
Loopback Dashdb connection pooling 

### ISSUE THREAD

**Issue by emmanuelpaul** [strongloop/loopback-connector-dashdb#60] opened 2017-08-08 05:36 UTC
Hi Team,

We have loopback app developed from bluemix and we are sending request and response from so many users . When there was concurrent users request the dashdb stuck with lock_held errors from dashdb monitoring with so much of user connection opened , **Can you please help me how to mange the loopback dashdb connection pooling.**

Regards,
Emmanuel Paul
ememmanu@in.ibm.com
91-9742260218

**Comment by kjdelisle** [comment] 2017-08-31 19:18
@emmanuelpaul You'll need to provide a reproduction application in the form of a github repository that we can use to diagnose the issue, and then we can take a look.

If you've already solved this problem, please let me know so I can close this issue.

**Comment by kjdelisle** [comment] 2017-08-31 19:19
@emmanuelpaul Sorry, a correction:

Our policy is to close issues that do not provide reproductions, my mistake.
If you can provide one, I'll re-open this ticket.

**Comment by emmanuelpaul** [comment] 2017-08-31 23:58
Hi Team,
 
                 Please provide the information how to manage the connection pooling in the dashdb. We have the issue when concurrent user doing CURD operation on dashdb table and also the new connection are getting created without closing the existing after operation.
 
Thanks & Regards ,Emmanuel PaulApplication Specialist,GBS GD, IBM India Limited,D3 Block ,Manyata,NagawaraBangalore, India.Office - 080- 28063207Mobile : 91-9742260218E-mail :ememmanu@in.ibm.com
 
 
----- Original message -----From: Kevin Delisle <notifications@github.com>To: strongloop/loopback-connector-dashdb <loopback-connector-dashdb@noreply.github.com>Cc: emmanuelpaul <ememmanu@in.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [strongloop/loopback-connector-dashdb] Loopback Dashdb connection pooling (#60)Date: Fri, Sep 1, 2017 12:49 AM 
@emmanuelpaul Sorry, a correction:
Our policy is to close issues that do not provide reproductions, my mistake.If you can provide one, I'll re-open this ticket.

**Comment by kjdelisle** [comment] 2017-09-01 20:05
@emmanuelpaul I've discovered some options inside the loopback-ibmdb base connector that allows configuration of the connection pool's minimum and maximum size, and have opened a PR for it.

**Comment by kjdelisle** [comment] 2017-09-01 20:08
With respect to the original issue, I would need a reproduction to determine where the deadlocking is occurring.

**Comment by emmanuelpaul** [comment] 2017-09-04 09:27
Please check the below screenshot.
 

Thanks & Regards ,Emmanuel PaulApplication Specialist,GBS GD, IBM India Limited,D3 Block ,Manyata,NagawaraBangalore, India.Office - 080- 28063207Mobile : 91-9742260218E-mail :ememmanu@in.ibm.com
 
 
----- Original message -----From: Kevin Delisle <notifications@github.com>To: strongloop/loopback-connector-dashdb <loopback-connector-dashdb@noreply.github.com>Cc: emmanuelpaul <ememmanu@in.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [strongloop/loopback-connector-dashdb] Loopback Dashdb connection pooling (#60)Date: Sat, Sep 2, 2017 1:38 AM 
With respect to the original issue, I would need a reproduction to determine where the deadlocking is occurring.

**Comment by kjdelisle** [comment] 2017-09-04 13:35
@emmanuelpaul I don't see a screenshot; if you replied via email, it was most probably not attached in the correct way.
In any case, a screenshot is not sufficient reproduction of the issue. Please provide a link to a sample code repository so that we can observe and debug your issue.

**Comment by emmanuelpaul** [comment] 2017-09-04 14:08
Thanks & Regards ,Emmanuel PaulApplication Specialist,GBS GD, IBM India Limited,D3 Block ,Manyata,NagawaraBangalore, India.Office - 080- 28063207Mobile : 91-9742260218E-mail :ememmanu@in.ibm.com
 
 
----- Original message -----From: Kevin Delisle <notifications@github.com>To: strongloop/loopback-connector-dashdb <loopback-connector-dashdb@noreply.github.com>Cc: emmanuelpaul <ememmanu@in.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [strongloop/loopback-connector-dashdb] Loopback Dashdb connection pooling (#60)Date: Mon, Sep 4, 2017 7:05 PM 
@emmanuelpaul I don't see a screenshot; if you replied via email, it was most probably not attached in the correct way.In any case, a screenshot is not sufficient reproduction of the issue. Please provide a link to a sample code repository so that we can observe and debug your issue.

**Comment by kjdelisle** [comment] 2017-09-04 16:57
@emmanuelpaul Again, there is no screenshot available based on what you've sent.
Please go to https://github.com/strongloop/loopback-connector-dashdb/issues/60 to submit your information.

Since you have not made efforts to create an example codebase to reproduce the problem, I'll be closing this issue.

**Closed by kjdelisle** 2017-09-04 16:57 UTC
Labels: team-apex
